export { ok, insufficient, isOk, expectOk, type Computed, type Exclusion } from "./result";
export {
  rupeesToMinorUnits,
  minorUnitsToRupees,
  roundHalfToEven,
  sumMinorUnits,
  multiplyMinorUnits,
  safeRatio,
  bpsToRatio,
} from "./money";
export { isTrusted, untrustedReason, type TrustState } from "./trust";
export { addMonthsClamped, daysInMonth } from "./dates";
export { computeNetWorth, type AssetInput, type LiabilityInput, type NetWorth } from "./netWorth";
export {
  valuePosition,
  valuePortfolio,
  findPriceAsOf,
  allocationByAssetClass,
  concentrationByInstrument,
  flagConcentration,
  type PositionInput,
  type ValuationInput,
  type ValuedPosition,
  type PortfolioValuation,
  type AllocationSlice,
} from "./portfolio";
export {
  summarizeMonth,
  comparePlanVsActual,
  activityCategory,
  type PlanCategory,
  type PlanRecordInput,
  type MonthlyBudget,
  type ActivityInput,
  type PlanVsReality,
  type CategoryComparison,
  type Coverage,
} from "./budget";
export {
  computeGoalProgress,
  projectGoalCompletion,
  canAllocateToGoal,
  canWithdrawForOrdinarySpending,
  isProtectedGoal,
  activeGoalsByPriority,
  type GoalInput,
  type GoalActivityInput,
  type GoalProgress,
  type GoalProjection,
  type GoalLifecycle,
  type AllocationCheck,
} from "./goals";
export {
  splitEmiByPayer,
  emiBurdenForPayer,
  projectEmiRelease,
  type LiabilityDetail,
  type PayerSplitInput,
  type PayerShare,
  type EmiPaymentInput,
  type ReleaseSchedule,
} from "./liabilities";
export {
  computeCagr,
  computeXirr,
  computeProfitAndLoss,
  netPresentValue,
  MIN_ANNUALIZATION_DAYS,
  type CagrInput,
  type CashFlow,
  type ProfitAndLoss,
} from "./returns";
export {
  PERIOD_OPTIONS,
  isPeriodKey,
  periodLabel,
  resolvePeriod,
  precedingRange,
  isMonthAligned,
  sameRangePriorYear,
  rangeContains,
  rangeDurationDays,
  monthsInRange,
  periodMonthOf,
  financialYearStart,
  financialYearLabel,
  type PeriodKey,
  type PeriodOption,
  type DateRange,
  type ResolveOptions,
  type MonthCoverage,
} from "./periods";
export {
  computePeriodMetrics,
  comparePeriods,
  comparePlannedAllocation,
  endingPeriodMonth,
  type PeriodCoverage,
  type BudgetTotals,
  type PeriodMetrics,
  type PeriodComparison,
  type MetricVariance,
  type ActivityFilter,
  type FilterableActivity,
  type AllocationComparisonRow,
} from "./analytics";
