export {
  ok,
  insufficient,
  isOk,
  expectOk,
  type Computed,
  type Exclusion,
} from "./result";
export {
  rupeesToMinorUnits,
  minorUnitsToRupees,
  roundHalfToEven,
  sumMinorUnits,
  multiplyMinorUnits,
  safeRatio,
  bpsToRatio,
} from "./money";
export { isTrusted, untrustedReason, type TrustState } from "./trust";
export { addMonthsClamped, daysInMonth, daysBetween } from "./dates";
export {
  computeNetWorth,
  type AssetInput,
  type LiabilityInput,
  type NetWorth,
} from "./netWorth";
export {
  valuePosition,
  valuePortfolio,
  findPriceAsOf,
  allocationByAssetClass,
  concentrationByInstrument,
  flagConcentration,
  type PositionInput,
  type ValuationInput,
  type ValuedPosition,
  type PortfolioValuation,
  type AllocationSlice,
} from "./portfolio";
export {
  summarizeMonth,
  comparePlanVsActual,
  activityCategory,
  type PlanCategory,
  type PlanRecordInput,
  type MonthlyBudget,
  type ActivityInput,
  type PlanVsReality,
  type CategoryComparison,
  type Coverage,
} from "./budget";
export {
  computeGoalProgress,
  projectGoalCompletion,
  canAllocateToGoal,
  canWithdrawForOrdinarySpending,
  isProtectedGoal,
  activeGoalsByPriority,
  withStatedBalance,
  type GoalInput,
  type GoalActivityInput,
  type GoalProgress,
  type GoalProjection,
  type GoalLifecycle,
  type AllocationCheck,
} from "./goals";
export {
  splitEmiByPayer,
  emiBurdenForPayer,
  projectEmiRelease,
  type LiabilityDetail,
  type PayerSplitInput,
  type PayerShare,
  type EmiPaymentInput,
  type ReleaseSchedule,
} from "./liabilities";
export {
  computeCagr,
  computeXirr,
  computeProfitAndLoss,
  netPresentValue,
  MIN_ANNUALIZATION_DAYS,
  type CagrInput,
  type CashFlow,
  type ProfitAndLoss,
} from "./returns";
export {
  PERIOD_OPTIONS,
  isPeriodKey,
  periodLabel,
  resolvePeriod,
  precedingRange,
  isMonthAligned,
  sameRangePriorYear,
  rangeContains,
  rangeDurationDays,
  monthsInRange,
  periodMonthOf,
  financialYearStart,
  financialYearLabel,
  type PeriodKey,
  type PeriodOption,
  type DateRange,
  type ResolveOptions,
  type MonthCoverage,
} from "./periods";
export {
  computePeriodMetrics,
  comparePeriods,
  comparePlannedAllocation,
  endingPeriodMonth,
  type PeriodCoverage,
  type BudgetTotals,
  type PeriodMetrics,
  type PeriodComparison,
  type MetricVariance,
  type ActivityFilter,
  type FilterableActivity,
  type AllocationComparisonRow,
} from "./analytics";
export {
  adjustmentKey,
  effectiveAdjustments,
  resolveEffectiveValue,
  applyAdjustment,
  previewAdjustment,
  type AdjustmentInput,
  type AdjustmentMode,
  type AdjustmentPreview,
  type AdjustmentUnit,
  type EffectiveValue,
} from "./adjustments";
export {
  aggregateTrust,
  buildInsight,
  buildMonthlySeries,
  buildDecomposition,
  buildScenarioResult,
  SCENARIO_DISCLAIMER,
  type InsightSeverity,
  type ProvenanceKind,
  type ProvenanceRef,
  type AggregateTrust,
  type MetricUnit,
  type MetricDefinition,
  type Insight,
  type TimeSeriesPoint,
  type DecompositionStepKind,
  type DecompositionStep,
  type Decomposition,
  type ScenarioAssumptions,
  type ScenarioResult,
} from "./insight";
export {
  projectFutureValue,
  monthsUntilTarget,
  simulateDebtPrepayment,
  PROJECTION_SEARCH_LIMIT_MONTHS,
  AMORTIZATION_SEARCH_LIMIT_MONTHS,
  type FutureValueInput,
  type DebtAmortizationResult,
} from "./scenarios";
export {
  detectGoalMilestones,
  detectLiabilityMilestones,
  detectEmergencyFundMilestone,
  detectSavingsRateMilestone,
  detectPortfolioValueMilestones,
  PORTFOLIO_VALUE_MILESTONE_THRESHOLDS,
  type Milestone,
  type MilestoneKind,
  type GoalMilestoneCandidate,
  type LiabilityMilestoneCandidate,
  type PortfolioValueThreshold,
} from "./milestones";
export {
  EMERGENCY_FUND_TARGET_MONTHS,
  computeEmergencyFundTargetMinorUnits,
  computeEmergencyFundRunwayMonths,
  validateEmergencyFundTopUp,
  type EmergencyFundTopUpValidation,
} from "./emergencyFund";
export {
  OVERALL_SAVINGS_RATE_MILESTONE_RATIO,
  computeOverallSavingsRate,
  type OverallSavingsRateInput,
} from "./savingsRate";
export {
  planRecordToTimelineEntry,
  activityToTimelineEntry,
  positionSnapshotToTimelineEntry,
  buildWealthTimeline,
  type TimelineBucket,
  type TimelineEntry,
  type PlanRecordTimelineInput,
  type ActivityTimelineInput,
  type PositionSnapshotTimelineInput,
} from "./timeline";
export {
  DASHBOARD_WIDGET_CATALOG,
  defaultDashboardLayoutPreferences,
  normalizeDashboardLayoutPreferences,
  resolveVisibleDashboardWidgets,
  type DashboardWidgetDefinition,
  type DashboardDensity,
  type DashboardWidgetPreference,
  type DashboardLayoutPreferences,
  type ResolvedDashboardWidget,
} from "./dashboardLayout";
