import Link from "next/link";
import { Card } from "../../../components/Primitives";
import { db } from "../../../lib/db";
import { formatDate } from "../../../presentation/format";
import { getReport, type ReportLine } from "../../../views/reportView";

export const dynamic = "force-dynamic";

const KIND_LABEL: Record<ReportLine["kind"], string> = {
  fact: "Fact",
  inference: "Inference",
  recommendation: "Recommendation",
};

const KIND_BADGE_CLASS: Record<ReportLine["kind"], string> = {
  fact: "badge--muted",
  inference: "badge--caution",
  recommendation: "badge--accent",
};

/**
 * A printable, locally generated report. No external service is involved —
 * the browser's own "Print to PDF" is the export path, per
 * docs/24 ("free reporting"): a saved/downloadable report is the
 * requirement, not any particular file format or a mail server.
 */
export default async function MarketReportPage() {
  const report = await getReport(db);

  return (
    <>
      <div className="page-header">
        <h1>Report</h1>
        <p>
          Generated {formatDate(report.generatedAt)}, as of {formatDate(report.asOf)}
          {report.periodMonth === null ? "" : ` (${report.periodMonth})`}. Every line
          below is a direct restatement of a figure computed elsewhere in the app —
          nothing here is generated by a model. Use your browser&apos;s print function to
          save this as a PDF.
        </p>
        <p className="note" style={{ marginTop: "0.4rem" }}>
          <Link href="/market">Back to Market</Link>
        </p>
      </div>

      <div className="stack">
        {report.sections.map((section) => (
          <Card key={section.title} title={section.title}>
            <ul
              style={{
                listStyle: "none",
                margin: 0,
                padding: 0,
                display: "flex",
                flexDirection: "column",
                gap: "0.5rem",
              }}
            >
              {section.lines.map((line, index) => (
                <li
                  key={index}
                  style={{ display: "flex", gap: "0.5rem", alignItems: "baseline" }}
                >
                  <span className={`badge ${KIND_BADGE_CLASS[line.kind]}`}>
                    {KIND_LABEL[line.kind]}
                  </span>
                  <span>{line.text}</span>
                </li>
              ))}
            </ul>
          </Card>
        ))}
      </div>
    </>
  );
}
