import { Card } from "../../components/Primitives";
import { db } from "../../lib/db";
import { formatDate, formatPeriodMonth } from "../../presentation/format";
import { getMonthlyReviewReport } from "../../views/monthlyReviewView";
import type { ReportLine } from "../../views/reportView";

export const dynamic = "force-dynamic";

const KIND_LABEL: Record<ReportLine["kind"], string> = {
  fact: "Fact",
  inference: "Inference",
  recommendation: "Recommendation",
};

const KIND_BADGE_CLASS: Record<ReportLine["kind"], string> = {
  fact: "badge--muted",
  inference: "badge--caution",
  recommendation: "badge--accent",
};

/**
 * Monthly Financial Review (v1.1.1 F9).
 *
 * The same locally generated, rule-based Report structure the Market
 * report (M10) and the Daily Brief (IM-07) already use, scoped to the most
 * recently completed month instead of "right now." No model is involved —
 * every line restates a figure an existing screen already computed for
 * that month.
 */
export default async function MonthlyReviewPage() {
  const report = await getMonthlyReviewReport(db);

  return (
    <>
      <div className="page-header">
        <h1>Monthly Review</h1>
        <p>
          Generated {formatDate(report.generatedAt)}
          {report.periodMonth === null ? "" : ` for ${formatPeriodMonth(report.periodMonth)}`}.
          Every line below is a direct restatement of a figure computed elsewhere in the
          app — nothing here is generated by a model. Use your browser&apos;s print
          function to save this as a PDF.
        </p>
      </div>

      <div className="stack">
        {report.sections.map((section) => (
          <Card key={section.title} title={section.title}>
            <ul
              style={{
                listStyle: "none",
                margin: 0,
                padding: 0,
                display: "flex",
                flexDirection: "column",
                gap: "0.5rem",
              }}
            >
              {section.lines.map((line, index) => (
                <li
                  key={index}
                  style={{ display: "flex", gap: "0.5rem", alignItems: "baseline" }}
                >
                  <span className={`badge ${KIND_BADGE_CLASS[line.kind]}`}>
                    {KIND_LABEL[line.kind]}
                  </span>
                  <span>{line.text}</span>
                </li>
              ))}
            </ul>
          </Card>
        ))}
      </div>
    </>
  );
}
